version: '3.8'

services:
  api_ylab_test:
    container_name: api_ylab_test
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      DATABASE_PORT: "$DATABASE_PORT"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_HOST: "$POSTGRES_HOST"
      POSTGRES_HOSTNAME: "$POSTGRES_HOSTNAME"
    entrypoint: sh -c "alembic upgrade head && python -m pytest [...]"
    volumes:
      - shared-volume:/api/generated_files
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    depends_on:
      db_ylab_test:
        condition: service_healthy


  db_ylab_test:
    container_name: db_ylab_test
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "hw_user", "-d", "homework"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s


networks:
  ylab_network:
    name: ylab_network
volumes:
  postgres_data:
  shared-volume:
